-- SPPG Insight Indonesia · Supabase schema
-- Run this file in the Supabase SQL Editor, then create an Auth user and add
-- its UUID to public.admin_users using the final INSERT example below.

create schema if not exists private;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.sppg_records (
  id text primary key,
  no integer not null,
  provinsi text not null,
  kabkota text not null,
  alamat text not null,
  yayasan text not null,
  pulau text not null check (pulau in ('Jawa', 'Luar Jawa')),
  lat double precision not null,
  lng double precision not null,
  geoprov text,
  location_accuracy text not null default 'centroid_kabkota' check (location_accuracy in ('centroid_kabkota', 'alamat_presisi')),
  flags jsonb not null default '[]'::jsonb check (jsonb_typeof(flags) = 'array'),
  status_operasional text not null default 'belum_diverifikasi' check (status_operasional in ('belum_diverifikasi', 'persiapan', 'operasional', 'nonaktif')),
  kapasitas_porsi integer check (kapasitas_porsi is null or kapasitas_porsi >= 0),
  penerima_manfaat integer check (penerima_manfaat is null or penerima_manfaat >= 0),
  tanggal_berdiri date,
  last_verified_at timestamptz,
  catatan_operasional text check (catatan_operasional is null or length(catatan_operasional) <= 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create unique index if not exists sppg_records_no_idx on public.sppg_records(no);
create index if not exists sppg_records_provinsi_idx on public.sppg_records(provinsi);
create index if not exists sppg_records_status_idx on public.sppg_records(status_operasional);

-- Public API surface deliberately excludes internal notes and actor metadata.
create or replace view public.sppg_public as
select id, no, provinsi, kabkota, alamat, yayasan, pulau, lat, lng, geoprov,
       location_accuracy, flags, status_operasional, kapasitas_porsi,
       penerima_manfaat, tanggal_berdiri, last_verified_at, updated_at
from public.sppg_records;

create table if not exists public.province_context (
  provinsi text primary key,
  population_target bigint check (population_target is null or population_target >= 0),
  target_portions bigint check (target_portions is null or target_portions >= 0),
  school_count integer check (school_count is null or school_count >= 0),
  stunting_rate numeric(5,2) check (stunting_rate is null or stunting_rate between 0 and 100),
  poverty_rate numeric(5,2) check (poverty_rate is null or poverty_rate between 0 and 100),
  period text,
  source_name text,
  source_url text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.sppg_audit_log (
  id bigint generated by default as identity primary key,
  sppg_id text not null,
  changed_by uuid references auth.users(id),
  changed_at timestamptz not null default now(),
  before_record jsonb,
  after_record jsonb not null
);

create or replace function private.is_sppg_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users where user_id = (select auth.uid())
  );
$$;

create or replace function private.touch_sppg_record()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  new.updated_by = (select auth.uid());
  return new;
end;
$$;

create or replace function private.audit_sppg_record()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.sppg_audit_log (sppg_id, changed_by, before_record, after_record)
  values (new.id, (select auth.uid()), to_jsonb(old), to_jsonb(new));
  return new;
end;
$$;

create or replace function private.touch_province_context()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  new.updated_by = (select auth.uid());
  return new;
end;
$$;

drop trigger if exists sppg_records_touch on public.sppg_records;
create trigger sppg_records_touch before update on public.sppg_records
for each row execute function private.touch_sppg_record();

drop trigger if exists sppg_records_audit on public.sppg_records;
create trigger sppg_records_audit after update on public.sppg_records
for each row execute function private.audit_sppg_record();

drop trigger if exists province_context_touch on public.province_context;
create trigger province_context_touch before update on public.province_context
for each row execute function private.touch_province_context();

alter table public.admin_users enable row level security;
alter table public.sppg_records enable row level security;
alter table public.province_context enable row level security;
alter table public.sppg_audit_log enable row level security;

drop policy if exists "admin can identify self" on public.admin_users;
create policy "admin can identify self" on public.admin_users for select to authenticated
using (user_id = (select auth.uid()));

drop policy if exists "public can read sppg" on public.sppg_records;
drop policy if exists "admin can read sppg" on public.sppg_records;
create policy "admin can read sppg" on public.sppg_records for select to authenticated using ((select private.is_sppg_admin()));
drop policy if exists "admin can insert sppg" on public.sppg_records;
create policy "admin can insert sppg" on public.sppg_records for insert to authenticated with check ((select private.is_sppg_admin()));
drop policy if exists "admin can update sppg" on public.sppg_records;
create policy "admin can update sppg" on public.sppg_records for update to authenticated using ((select private.is_sppg_admin())) with check ((select private.is_sppg_admin()));
drop policy if exists "admin can delete sppg" on public.sppg_records;
create policy "admin can delete sppg" on public.sppg_records for delete to authenticated using ((select private.is_sppg_admin()));

drop policy if exists "public can read province context" on public.province_context;
create policy "public can read province context" on public.province_context for select to anon, authenticated using (true);
drop policy if exists "admin can insert province context" on public.province_context;
create policy "admin can insert province context" on public.province_context for insert to authenticated with check ((select private.is_sppg_admin()));
drop policy if exists "admin can update province context" on public.province_context;
create policy "admin can update province context" on public.province_context for update to authenticated using ((select private.is_sppg_admin())) with check ((select private.is_sppg_admin()));

drop policy if exists "admin can read audit log" on public.sppg_audit_log;
create policy "admin can read audit log" on public.sppg_audit_log for select to authenticated using ((select private.is_sppg_admin()));

grant usage on schema public to anon, authenticated;
revoke all on public.sppg_records from anon;
grant select on public.sppg_public, public.province_context to anon, authenticated;
grant select on public.sppg_records to authenticated;
grant select on public.admin_users, public.sppg_audit_log to authenticated;
grant insert, update, delete on public.sppg_records to authenticated;
grant insert, update on public.province_context to authenticated;
grant usage, select on sequence public.sppg_audit_log_id_seq to authenticated;

-- After creating a user in Authentication > Users, run once with its UUID:
-- insert into public.admin_users (user_id) values ('00000000-0000-0000-0000-000000000000');
