-- Upgrade an existing SPPG Insight v2 database to the v3 operational workflow.
-- Fresh installations may run supabase/schema.sql instead.
begin;

create extension if not exists pgcrypto;
create schema if not exists private;

alter table public.admin_users add column if not exists display_name text;
alter table public.admin_users add column if not exists role text not null default 'viewer';
alter table public.admin_users add column if not exists active boolean not null default true;
alter table public.admin_users add column if not exists updated_at timestamptz not null default now();

create table if not exists public.import_batches (
  id uuid primary key default gen_random_uuid(), filename text not null,
  file_type text not null check (file_type in ('csv', 'xlsx')),
  total_rows integer not null default 0, added_rows integer not null default 0,
  changed_rows integer not null default 0, unchanged_rows integer not null default 0,
  invalid_rows integer not null default 0,
  status text not null default 'preview' check (status in ('preview', 'committed', 'failed', 'rolled_back')),
  mapping jsonb not null default '{}'::jsonb, created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(), committed_at timestamptz
);

alter table public.sppg_records add column if not exists workflow_status text not null default 'published';
alter table public.sppg_records add column if not exists assigned_to uuid references auth.users(id);
alter table public.sppg_records add column if not exists review_notes text;
alter table public.sppg_records add column if not exists verified_by uuid references auth.users(id);
alter table public.sppg_records add column if not exists verified_at timestamptz;
alter table public.sppg_records add column if not exists approved_by uuid references auth.users(id);
alter table public.sppg_records add column if not exists approved_at timestamptz;
alter table public.sppg_records add column if not exists published_at timestamptz;
alter table public.sppg_records add column if not exists version integer not null default 1;
alter table public.sppg_records add column if not exists source_batch_id uuid references public.import_batches(id);

create table if not exists public.import_batch_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.import_batches(id) on delete cascade,
  row_number integer not null, record_id text,
  action text not null check (action in ('added', 'changed', 'unchanged', 'invalid')),
  payload jsonb not null, previous_record jsonb,
  validation_errors jsonb not null default '[]'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.record_comments (
  id bigint generated by default as identity primary key,
  sppg_id text not null references public.sppg_records(id) on delete cascade,
  body text not null check (length(body) between 1 and 2000),
  author_id uuid not null references auth.users(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.sppg_evidence (
  id uuid primary key default gen_random_uuid(),
  sppg_id text not null references public.sppg_records(id) on delete cascade,
  storage_path text not null unique, file_name text not null, mime_type text not null,
  file_size integer not null check (file_size between 1 and 5242880),
  note text check (note is null or length(note) <= 500),
  uploaded_by uuid not null references auth.users(id), created_at timestamptz not null default now()
);
alter table public.sppg_audit_log add column if not exists action text not null default 'updated';

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'admin_users_role_check') then
    alter table public.admin_users add constraint admin_users_role_check check (role in ('viewer', 'operator', 'verifier', 'approver', 'super_admin'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'sppg_records_workflow_check') then
    alter table public.sppg_records add constraint sppg_records_workflow_check check (workflow_status in ('draft', 'review', 'revision', 'verified', 'published', 'archived'));
  end if;
end $$;

create unique index if not exists sppg_records_no_idx on public.sppg_records(no);
create index if not exists sppg_records_workflow_idx on public.sppg_records(workflow_status);
create index if not exists import_batch_items_batch_idx on public.import_batch_items(batch_id);
create index if not exists record_comments_sppg_idx on public.record_comments(sppg_id, created_at desc);
create index if not exists sppg_evidence_sppg_idx on public.sppg_evidence(sppg_id, created_at desc);
create index if not exists sppg_audit_log_changed_idx on public.sppg_audit_log(changed_at desc);

drop view if exists public.sppg_public;
create view public.sppg_public as
select id, no, provinsi, kabkota, alamat, yayasan, pulau, lat, lng, geoprov,
       location_accuracy, flags, status_operasional, kapasitas_porsi,
       penerima_manfaat, tanggal_berdiri, last_verified_at, workflow_status,
       published_at, updated_at, version
from public.sppg_records where workflow_status = 'published';

create or replace function private.current_sppg_role() returns text
language sql stable security definer set search_path = '' as $$
  select role from public.admin_users where user_id = (select auth.uid()) and active = true
$$;
create or replace function private.is_sppg_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.admin_users where user_id = (select auth.uid()) and active = true)
$$;
create or replace function private.can_operate() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce((select private.current_sppg_role()) in ('operator', 'verifier', 'approver', 'super_admin'), false)
$$;
create or replace function private.can_import() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce((select private.current_sppg_role()) in ('operator', 'super_admin'), false)
$$;
create or replace function private.is_super_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select coalesce((select private.current_sppg_role()) = 'super_admin', false)
$$;
create or replace function private.touch_sppg_record() returns trigger
language plpgsql security invoker set search_path = '' as $$
begin new.updated_at = now(); new.updated_by = (select auth.uid()); if tg_op = 'UPDATE' then new.version = old.version + 1; end if; return new; end;
$$;
create or replace function private.validate_workflow_transition() returns trigger
language plpgsql security invoker set search_path = '' as $$
declare actor_role text := (select private.current_sppg_role());
begin
  if tg_op = 'INSERT' and actor_role <> 'super_admin' and new.workflow_status not in ('draft', 'review') then raise exception 'New records must start as draft or review'; end if;
  if tg_op = 'UPDATE' and old.workflow_status is distinct from new.workflow_status then
    if actor_role = 'operator' and not (new.workflow_status = 'review' and old.workflow_status in ('draft', 'revision', 'published')) then raise exception 'Operator cannot perform this transition'; end if;
    if actor_role = 'verifier' and not (old.workflow_status = 'review' and new.workflow_status in ('revision', 'verified')) then raise exception 'Verifier cannot perform this transition'; end if;
    if actor_role = 'approver' and not (old.workflow_status = 'verified' and new.workflow_status in ('revision', 'published')) then raise exception 'Approver cannot perform this transition'; end if;
    if actor_role = 'viewer' or actor_role is null then raise exception 'Viewer cannot change workflow'; end if;
  end if;
  if tg_op = 'UPDATE' and actor_role <> 'super_admin' and old.workflow_status in ('verified', 'published') and old.workflow_status = new.workflow_status
     and (to_jsonb(new) - array['updated_at','updated_by','version']) is distinct from (to_jsonb(old) - array['updated_at','updated_by','version']) then
    raise exception 'Locked records must return to review before their content changes';
  end if;
  if tg_op = 'UPDATE' and actor_role <> 'super_admin'
     and (to_jsonb(new) - array['updated_at','updated_by','version','workflow_status','review_notes','verified_by','verified_at','approved_by','approved_at','published_at'])
       is distinct from
       (to_jsonb(old) - array['updated_at','updated_by','version','workflow_status','review_notes','verified_by','verified_at','approved_by','approved_at','published_at']) then
    if actor_role = 'operator' and old.workflow_status not in ('draft', 'revision', 'published') then raise exception 'Operator cannot edit content at this stage'; end if;
    if actor_role = 'verifier' and old.workflow_status not in ('review', 'revision') then raise exception 'Verifier cannot edit content at this stage'; end if;
    if actor_role = 'approver' then raise exception 'Approver can decide workflow but cannot edit record content'; end if;
  end if;
  return new;
end;
$$;
create or replace function private.audit_sppg_record() returns trigger
language plpgsql security definer set search_path = '' as $$
declare audit_action text;
begin
  audit_action := case when tg_op = 'INSERT' then 'created' when old.workflow_status is distinct from new.workflow_status then 'workflow_' || new.workflow_status else 'updated' end;
  insert into public.sppg_audit_log (sppg_id, action, changed_by, before_record, after_record)
  values (new.id, audit_action, (select auth.uid()), case when tg_op = 'INSERT' then null else to_jsonb(old) end, to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists sppg_records_touch on public.sppg_records;
create trigger sppg_records_touch before insert or update on public.sppg_records for each row execute function private.touch_sppg_record();
drop trigger if exists sppg_records_workflow_guard on public.sppg_records;
create trigger sppg_records_workflow_guard before insert or update on public.sppg_records for each row execute function private.validate_workflow_transition();
drop trigger if exists sppg_records_audit on public.sppg_records;
create trigger sppg_records_audit after insert or update on public.sppg_records for each row execute function private.audit_sppg_record();

alter table public.admin_users enable row level security;
alter table public.sppg_records enable row level security;
alter table public.import_batches enable row level security;
alter table public.import_batch_items enable row level security;
alter table public.record_comments enable row level security;
alter table public.sppg_evidence enable row level security;
alter table public.sppg_audit_log enable row level security;

drop policy if exists "admin can identify self" on public.admin_users;
create policy "admin can identify self" on public.admin_users for select to authenticated using (user_id = (select auth.uid()) or (select private.is_super_admin()));
drop policy if exists "super admin can update team" on public.admin_users;
create policy "super admin can update team" on public.admin_users for update to authenticated using ((select private.is_super_admin())) with check ((select private.is_super_admin()));
drop policy if exists "admin can read sppg" on public.sppg_records;
create policy "admin can read sppg" on public.sppg_records for select to authenticated using ((select private.is_sppg_admin()));
drop policy if exists "admin can insert sppg" on public.sppg_records;
create policy "admin can insert sppg" on public.sppg_records for insert to authenticated with check ((select private.can_operate()));
drop policy if exists "admin can update sppg" on public.sppg_records;
create policy "admin can update sppg" on public.sppg_records for update to authenticated using ((select private.can_operate())) with check ((select private.can_operate()));
drop policy if exists "super admin can delete sppg" on public.sppg_records;
drop policy if exists "admin can delete sppg" on public.sppg_records;
create policy "super admin can delete sppg" on public.sppg_records for delete to authenticated using ((select private.is_super_admin()));
drop policy if exists "admin can manage import batches" on public.import_batches;
create policy "admin can manage import batches" on public.import_batches for all to authenticated using ((select private.can_import())) with check ((select private.can_import()));
drop policy if exists "admin can manage import items" on public.import_batch_items;
create policy "admin can manage import items" on public.import_batch_items for all to authenticated using ((select private.can_import())) with check ((select private.can_import()));
drop policy if exists "admin can insert province context" on public.province_context;
create policy "admin can insert province context" on public.province_context for insert to authenticated with check ((select private.can_import()));
drop policy if exists "admin can update province context" on public.province_context;
create policy "admin can update province context" on public.province_context for update to authenticated using ((select private.can_import())) with check ((select private.can_import()));
drop policy if exists "admin can read comments" on public.record_comments;
create policy "admin can read comments" on public.record_comments for select to authenticated using ((select private.is_sppg_admin()));
drop policy if exists "admin can add comments" on public.record_comments;
create policy "admin can add comments" on public.record_comments for insert to authenticated with check ((select private.can_operate()) and author_id = (select auth.uid()));
drop policy if exists "author can update comments" on public.record_comments;
create policy "author can update comments" on public.record_comments for update to authenticated using (author_id = (select auth.uid()) or (select private.is_super_admin()));
drop policy if exists "author can delete comments" on public.record_comments;
create policy "author can delete comments" on public.record_comments for delete to authenticated using (author_id = (select auth.uid()) or (select private.is_super_admin()));
drop policy if exists "admin can read evidence" on public.sppg_evidence;
create policy "admin can read evidence" on public.sppg_evidence for select to authenticated using ((select private.is_sppg_admin()));
drop policy if exists "admin can add evidence" on public.sppg_evidence;
create policy "admin can add evidence" on public.sppg_evidence for insert to authenticated with check ((select private.can_operate()) and uploaded_by = (select auth.uid()));
drop policy if exists "uploader can delete evidence" on public.sppg_evidence;
create policy "uploader can delete evidence" on public.sppg_evidence for delete to authenticated using (uploaded_by = (select auth.uid()) or (select private.is_super_admin()));
drop policy if exists "admin can read audit log" on public.sppg_audit_log;
create policy "admin can read audit log" on public.sppg_audit_log for select to authenticated using ((select private.is_sppg_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('sppg-evidence', 'sppg-evidence', false, 5242880, array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict (id) do update set public = false, file_size_limit = 5242880, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "admin can read evidence files" on storage.objects;
create policy "admin can read evidence files" on storage.objects for select to authenticated using (bucket_id = 'sppg-evidence' and (select private.is_sppg_admin()));
drop policy if exists "admin can upload evidence files" on storage.objects;
create policy "admin can upload evidence files" on storage.objects for insert to authenticated with check (bucket_id = 'sppg-evidence' and (select private.can_operate()));
drop policy if exists "admin can delete evidence files" on storage.objects;
create policy "admin can delete evidence files" on storage.objects for delete to authenticated using (bucket_id = 'sppg-evidence' and ((owner_id = (select auth.uid()::text)) or (select private.is_super_admin())));

grant select on public.sppg_public to anon, authenticated;
grant select on public.admin_users, public.sppg_records, public.import_batches, public.import_batch_items, public.record_comments, public.sppg_evidence, public.sppg_audit_log to authenticated;
grant insert, update on public.admin_users to authenticated;
grant insert, update, delete on public.sppg_records, public.import_batches, public.import_batch_items, public.record_comments, public.sppg_evidence to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
